FROM node:10-alpine

ENV NPM_VERSION=6.7.0 \
    IONIC_VERSION=5.3.0

RUN apk add --no-cache bash git

RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories
RUN apk add --no-cache xxd@testing

RUN rm -rf /tmp/* && \
    rm -rf /var/cache/apk/*

RUN npm install -g npm@"$NPM_VERSION" npmrc ionic@"$IONIC_VERSION" firebase-tools typings bit-bin

RUN mkdir myApp

### Clean
RUN npm cache clear --force

VOLUME ["/myApp"]

WORKDIR myApp
EXPOSE 8100 35729

CMD ["ionic", "serve"]
